### ISSUE TITLE
Latest version fabric 1.20.1 crash

### ISSUE THREAD

**Issue by Proxwian** [Scouter456/Nether_Depths_Upgrade#31]
[crash-2024-03-03_00.47.23-client.txt](https://github.com/Scouter456/Nether_Depths_Upgrade/files/14470860/crash-2024-03-03_00.47.23-client.txt)

netherdepthsupgrade-fabric-3.1.4-1.20.jar

**Comment by AusPakeha** [comment]
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [netherdepthsupgrade.mixins.json:render.ScreenFogEffect from mod netherdepthsupgrade] from phase [DEFAULT] in config [netherdepthsupgrade.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 13 more

**Comment by RyanSalad** [comment]
> [crash-2024-03-03_00.47.23-client.txt](https://github.com/Scouter456/Nether_Depths_Upgrade/files/14470860/crash-2024-03-03_00.47.23-client.txt)
> netherdepthsupgrade-fabric-3.1.4-1.20.jar

I'm getting the same crash on 3.1.4 for 1.19.2. Same crash report text and everything

**Comment by Scouter456** [comment]
Should be fixed in the latest version
